export type Verification = "Verified" | "Government-reported" | "Company-reported";

export type Project = {
  slug: string;
  name: string;
  developer: string;
  companySlug: string;
  location: string;
  region: string;
  technology: string;
  capacity: string;
  stage: number;
  stageLabel: string;
  commitment: number;
  status: string;
  summary: string;
  latest: string;
  latestDate: string;
  next: string;
  nextOwner: string;
  blocker: string;
  confidence: "High" | "Medium" | "Low";
  verification: Verification;
  source: string;
  sourceLabel: string;
  programs: string[];
  x: number | null;
  y: number | null;
};

export const stages = [
  { label: "Interest", summary: "Exploring the idea", definition: "Public interest or exploratory statement." },
  { label: "Preliminary", summary: "Early study or nonbinding agreement", definition: "MOU, LOI, reservation, or early study." },
  { label: "Development", summary: "Site, engineering, or licensing work", definition: "Site control, engineering, formal licensing, or executed development work." },
  { label: "Contractual", summary: "Binding deal or committed capital", definition: "Binding offtake, equipment order, award, investment, or committed equity." },
  { label: "Ready", summary: "Final permit, finance, or go-ahead", definition: "Major permit, final investment decision, financial close, or notice to proceed." },
  { label: "Physical", summary: "Work or fuel at the site", definition: "Site preparation, first concrete, installation, fuel delivery, or fuel loading." },
  { label: "Operational", summary: "Criticality through commercial operation", definition: "Criticality, first power, grid connection, full power, or commercial operation." },
  { label: "Replication", summary: "Repeat units or fleet delivery", definition: "Repeat unit, fleet order, manufacturing cadence, or demonstrated learning." },
];

export const stageLabels = stages.map((stage) => stage.label);

export const projects: Project[] = [
  {
    slug: "natrium-kemmerer",
    name: "Natrium · Kemmerer Unit 1",
    developer: "TerraPower / US SFR Owner",
    companySlug: "terrapower",
    location: "Kemmerer, Wyoming",
    region: "West",
    technology: "Sodium-cooled fast reactor",
    capacity: "345 MWe + storage",
    stage: 6,
    stageLabel: "Physical deployment",
    commitment: 5,
    status: "Construction permitted",
    summary: "A commercial-scale advanced reactor demonstration replacing capacity near a retiring coal plant.",
    latest: "NRC issued construction permit CPAR-1; DOE later reported groundbreaking for the nuclear island.",
    latestDate: "2026-04",
    next: "Submit and secure the separate NRC operating license before fuel loading or operation.",
    nextOwner: "TerraPower and NRC",
    blocker: "Operating license, HALEU fuel availability, first-of-a-kind delivery",
    confidence: "High",
    verification: "Verified",
    source: "https://www.nrc.gov/reactors/new-reactors/advanced/who-were-working-with/past-license-activities/terrapower",
    sourceLabel: "NRC application record",
    programs: ["ARDP demonstration"],
    x: 22,
    y: 36,
  },
  {
    slug: "hermes-2",
    name: "Hermes 2",
    developer: "Kairos Power",
    companySlug: "kairos-power",
    location: "Oak Ridge, Tennessee",
    region: "South",
    technology: "Fluoride salt-cooled high-temperature reactor",
    capacity: "Two low-power test reactors",
    stage: 6,
    stageLabel: "Physical deployment",
    commitment: 5,
    status: "Construction underway",
    summary: "Two non-power test reactors intended to support commercial validation of Kairos Power's KP-FHR technology.",
    latest: "DOE reported Hermes 2 groundbreaking after the NRC issued two construction permits.",
    latestDate: "2026-04",
    next: "Complete nuclear construction, request operating licenses, then load fuel and test.",
    nextOwner: "Kairos Power and NRC",
    blocker: "Construction execution and later operating authorization",
    confidence: "High",
    verification: "Verified",
    source: "https://www.nrc.gov/reactors/non-power/new-facility-licensing/hermes2-kairos",
    sourceLabel: "NRC Hermes 2 record",
    programs: ["ARDP risk reduction"],
    x: 68,
    y: 62,
  },
  {
    slug: "long-mott-xe-100",
    name: "Long Mott · Xe-100",
    developer: "Long Mott Energy / X-energy / Dow",
    companySlug: "x-energy",
    location: "Calhoun County, Texas",
    region: "South",
    technology: "High-temperature gas-cooled reactor",
    capacity: "4 × 80 MWe + process heat",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "License review",
    summary: "A four-module industrial energy project designed to supply electricity and process heat at Dow's Seadrift site.",
    latest: "NRC environmental review concluded with an environmental assessment and finding of no significant impact.",
    latestDate: "2026-05",
    next: "Complete the safety review and obtain a construction permit; operation requires a later license.",
    nextOwner: "NRC and Long Mott Energy",
    blocker: "Construction-permit decision and TRISO fuel scale-up",
    confidence: "Medium",
    verification: "Verified",
    source: "https://www.nrc.gov/reactors/new-reactors/advanced/who-were-working-with/applicant-projects/long-mott",
    sourceLabel: "NRC Long Mott dashboard",
    programs: ["ARDP demonstration"],
    x: 51,
    y: 78,
  },
  {
    slug: "project-pele",
    name: "Project Pele",
    developer: "U.S. Department of Defense / BWXT",
    companySlug: "bwxt",
    location: "Idaho National Laboratory",
    region: "West",
    technology: "Transportable high-temperature gas reactor",
    capacity: "1–5 MWe",
    stage: 6,
    stageLabel: "Physical deployment",
    commitment: 4,
    status: "Prototype construction",
    summary: "A transportable microreactor demonstration for resilient military power, under DOE safety oversight.",
    latest: "DoD broke ground at INL for the prototype demonstration site.",
    latestDate: "2024-09",
    next: "Deliver the reactor module, complete safety review, assemble, fuel, and begin testing.",
    nextOwner: "DoD, BWXT, and DOE Idaho Operations",
    blocker: "Module delivery, authorization, and demonstration testing",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/ne/articles/department-defense-breaks-ground-project-pele-microreactor",
    sourceLabel: "DOE Project Pele update",
    programs: ["Project Pele"],
    x: 20,
    y: 28,
  },
  {
    slug: "kaleidos-dome",
    name: "Kaleidos · DOME test",
    developer: "Radiant Industries / NRIC",
    companySlug: "radiant-industries",
    location: "Idaho National Laboratory",
    region: "West",
    technology: "Gas-cooled microreactor",
    capacity: "Experiment",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "Conditional test slot",
    summary: "A planned fueled experiment in DOE's DOME microreactor test bed, subject to readiness milestones.",
    latest: "DOE conditionally selected Kaleidos for an initial DOME test slot.",
    latestDate: "2025-07",
    next: "Satisfy readiness gates, complete authorization, install the experiment, and conduct testing.",
    nextOwner: "Radiant, NRIC, and DOE",
    blocker: "Test readiness and DOE authorization",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/ne/demonstration-microreactor-experiments-dome",
    sourceLabel: "DOE DOME program",
    programs: ["DOME"],
    x: 24,
    y: 29,
  },
  {
    slug: "valar-ward-250",
    name: "Ward 250 critical experiment",
    developer: "Valar Atomics",
    companySlug: "valar-atomics",
    location: "Emery County, Utah",
    region: "West",
    technology: "Zero-power critical experiment",
    capacity: "No electricity generation",
    stage: 7,
    stageLabel: "Operational progress",
    commitment: 6,
    status: "Initial criticality achieved",
    summary: "A DOE-authorized zero-power criticality demonstration; it is evidence of reactor physics, not commercial operation.",
    latest: "The Ward 250 experiment achieved zero-power criticality outside a national laboratory.",
    latestDate: "2026-06",
    next: "Translate test results into a powered design, licensing basis, customer project, and repeatable delivery plan.",
    nextOwner: "Valar Atomics",
    blocker: "Powered demonstration, licensing, finance, and commercialization",
    confidence: "High",
    verification: "Government-reported",
    source: "https://www.energy.gov/articles/department-energy-celebrates-second-advanced-reactor-achieving-criticality",
    sourceLabel: "DOE criticality announcement",
    programs: ["Reactor Pilot Program"],
    x: 27,
    y: 48,
  },
  {
    slug: "aalo-x-critical-assembly",
    name: "Aalo Critical Test Reactor",
    developer: "Aalo Atomics",
    companySlug: "aalo-atomics",
    location: "Idaho National Laboratory",
    region: "West",
    technology: "Sodium-cooled zero-power critical reactor",
    capacity: "No electricity generation",
    stage: 7,
    stageLabel: "Operational progress",
    commitment: 6,
    status: "Initial criticality achieved",
    summary: "A full-scale zero-power core under DOE authorization; it validates reactor physics and systems but does not generate electricity.",
    latest: "Aalo reported that its Critical Test Reactor achieved a sustained chain reaction at 12:20 a.m. Mountain Time on July 4.",
    latestDate: "2026-07",
    next: "Build, license, fuel, and operate the separate 10 MWe Project Ascension reactor before claiming power deployment.",
    nextOwner: "Aalo Atomics, DOE, and NRC",
    blocker: "Power-reactor construction, NRC licensing, fuel, and commercial operation",
    confidence: "Medium",
    verification: "Company-reported",
    source: "https://www.linkedin.com/posts/aalo-atomics_on-july-4-2026-at-1220-am-mt-we-brought-activity-7479885863984713728-HTO7",
    sourceLabel: "Aalo criticality announcement on LinkedIn",
    programs: ["Reactor Pilot Program"],
    x: 19,
    y: 27,
  },
  {
    slug: "antares-mark-0",
    name: "Antares R1 Mark-0",
    developer: "Antares Nuclear",
    companySlug: "antares-nuclear",
    location: "Idaho National Laboratory",
    region: "West",
    technology: "High-temperature heat-pipe microreactor experiment",
    capacity: "Zero-power critical experiment",
    stage: 7,
    stageLabel: "Operational progress",
    commitment: 6,
    status: "Initial criticality achieved",
    summary: "A zero-power fueled experiment that validates reactor physics but does not generate electricity.",
    latest: "DOE reported that the Mark-0 completed zero-power fueled criticality at Idaho National Laboratory.",
    latestDate: "2026-06",
    next: "Complete further testing and establish the NRC licensing and customer pathway for a power-producing reactor.",
    nextOwner: "Antares Nuclear",
    blocker: "Powered demonstration, NRC licensing, fuel, and commercial project execution",
    confidence: "High",
    verification: "Government-reported",
    source: "https://www.energy.gov/articles/department-energy-celebrates-first-advanced-reactor-criticality",
    sourceLabel: "DOE criticality announcement",
    programs: ["Reactor Pilot Program"],
    x: 21,
    y: 30,
  },
  {
    slug: "atomic-alchemy-groves",
    name: "Groves pilot reactor",
    developer: "Atomic Alchemy",
    companySlug: "atomic-alchemy",
    location: "Caldwell County, Texas",
    region: "South",
    technology: "Test and isotope-production reactor",
    capacity: "Not disclosed by DOE",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "Atomic Alchemy's privately funded Groves project under DOE's Reactor Pilot Program pathway.",
    latest: "A DOE variance package identified the Groves project and its 40-acre Caldwell County site.",
    latestDate: "2026-01",
    next: "Complete the DOE safety basis, authorization, construction, and fuel-readiness gates before operation.",
    nextOwner: "Atomic Alchemy and DOE Idaho Operations",
    blocker: "DOE authorization, construction, and fuel readiness",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: 50,
    y: 76,
  },
  {
    slug: "deep-fission-dbr",
    name: "Deep Fission DBR pilot",
    developer: "Deep Fission",
    companySlug: "deep-fission",
    location: "Site not disclosed by DOE",
    region: "Undisclosed",
    technology: "Deep-borehole reactor",
    capacity: "Not disclosed by DOE",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "A DBR test-reactor project selected for DOE's Reactor Pilot Program; DOE has not published its site in the cited record.",
    latest: "DOE identified the DBR reactor in its advanced-reactor contractor variance package without publishing a site.",
    latestDate: "2026-01",
    next: "Disclose and authorize a site, complete the safety basis, and demonstrate construction and fuel readiness.",
    nextOwner: "Deep Fission and DOE Idaho Operations",
    blocker: "Site disclosure, DOE authorization, construction method, and fuel",
    confidence: "Low",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: null,
    y: null,
  },
  {
    slug: "last-energy-pwr-5",
    name: "PWR-5 pilot reactor",
    developer: "Last Energy",
    companySlug: "last-energy",
    location: "Texas A&M RELLIS Campus, Texas",
    region: "South",
    technology: "Small pressurized-water reactor",
    capacity: "Not disclosed by DOE",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "Last Energy's PWR-5 test project at the Texas A&M RELLIS campus under the DOE pilot pathway.",
    latest: "DOE identified PWR-5 and the Texas A&M RELLIS campus in its contractor variance package.",
    latestDate: "2026-01",
    next: "Complete site authorization, safety analysis, construction, and operating readiness under DOE oversight.",
    nextOwner: "Last Energy and DOE Idaho Operations",
    blocker: "DOE authorization, construction readiness, and fuel",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: 51,
    y: 72,
  },
  {
    slug: "oklo-aurora-pilot",
    name: "Aurora pilot reactor",
    developer: "Oklo",
    companySlug: "oklo",
    location: "Idaho National Laboratory",
    region: "West",
    technology: "Fast microreactor",
    capacity: "Not disclosed for pilot",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "One of two Oklo projects selected through DOE's Reactor Pilot Program.",
    latest: "DOE identified the Aurora reactor at Idaho National Laboratory in its contractor variance package.",
    latestDate: "2026-01",
    next: "Complete DOE authorization, site work, construction, fuel readiness, and critical testing.",
    nextOwner: "Oklo and DOE Idaho Operations",
    blocker: "DOE authorization, fuel fabrication, construction, and test readiness",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: 23,
    y: 32,
  },
  {
    slug: "oklo-pluto-pilot",
    name: "Pluto pilot reactor",
    developer: "Oklo",
    companySlug: "oklo",
    location: "Savannah River Site, South Carolina",
    region: "South",
    technology: "Fast test reactor",
    capacity: "Not disclosed for pilot",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "Oklo's second DOE pilot project, paired with an advanced-fuels facility near Savannah River National Laboratory.",
    latest: "DOE identified the Pluto reactor and Advanced Fuels Foundry location in its contractor variance package.",
    latestDate: "2026-01",
    next: "Complete DOE authorization, fuel-facility integration, construction, and critical-test readiness.",
    nextOwner: "Oklo and DOE Idaho Operations",
    blocker: "DOE authorization, fuel facility, construction, and test readiness",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: 76,
    y: 68,
  },
  {
    slug: "natura-acu-pilot",
    name: "Natura pilot · ACU",
    developer: "Natura Resources / Abilene Christian University",
    companySlug: "natura-resources",
    location: "Abilene Christian University, Texas",
    region: "South",
    technology: "Molten-salt research reactor",
    capacity: "Research reactor; output not disclosed",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "Natura Resources' university-based test-reactor project in DOE's Reactor Pilot Program.",
    latest: "DOE identified Abilene Christian University as the project site in its contractor variance package.",
    latestDate: "2026-01",
    next: "Complete the DOE authorization basis, site work, construction, fuel loading, and operating readiness.",
    nextOwner: "Natura Resources, ACU, and DOE Idaho Operations",
    blocker: "DOE authorization, university-site execution, and fuel",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: 47,
    y: 69,
  },
  {
    slug: "radiant-kaleidos-ripper-pilot",
    name: "Kaleidos + RiPPer pilot",
    developer: "Radiant Industries",
    companySlug: "radiant-industries",
    location: "Idaho National Laboratory",
    region: "West",
    technology: "Gas-cooled microreactor experiments",
    capacity: "Two test reactors; output not disclosed",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "Radiant's DOE pilot project covers the Kaleidos and RiPPer test reactors at Idaho National Laboratory.",
    latest: "DOE identified both reactors and their INL site in its contractor variance package.",
    latestDate: "2026-01",
    next: "Complete DOE authorization and readiness gates for construction, fuel loading, and critical testing.",
    nextOwner: "Radiant Industries and DOE Idaho Operations",
    blocker: "DOE authorization, test-bed sequencing, construction, and fuel",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: 25,
    y: 34,
  },
  {
    slug: "terrestrial-tetra-1",
    name: "TETRA-1 pilot reactor",
    developer: "Terrestrial Energy",
    companySlug: "terrestrial-energy",
    location: "Texas A&M RELLIS Campus, Texas",
    region: "South",
    technology: "Molten-salt test reactor",
    capacity: "Not disclosed by DOE",
    stage: 3,
    stageLabel: "Development commitment",
    commitment: 3,
    status: "DOE pilot development",
    summary: "Terrestrial Energy's TETRA-1 test project under the DOE Reactor Pilot Program pathway.",
    latest: "DOE identified TETRA-1 and the Texas A&M RELLIS campus in its contractor variance package.",
    latestDate: "2026-01",
    next: "Complete DOE authorization, site work, fuel preparation, construction, and critical-test readiness.",
    nextOwner: "Terrestrial Energy and DOE Idaho Operations",
    blocker: "DOE authorization, fuel-salt preparation, construction, and testing",
    confidence: "Medium",
    verification: "Government-reported",
    source: "https://www.energy.gov/sites/default/files/2026-04/NE_10CFR851_VariancePackage_Final_05JAN2026.pdf",
    sourceLabel: "DOE contractor variance package",
    programs: ["Reactor Pilot Program"],
    x: 54,
    y: 74,
  },
  {
    slug: "deployable-unity",
    name: "Unity critical experiment",
    developer: "Deployable Energy",
    companySlug: "deployable-energy",
    location: "Idaho National Laboratory",
    region: "West",
    technology: "Zero-power microreactor experiment",
    capacity: "No electricity generation",
    stage: 7,
    stageLabel: "Operational progress",
    commitment: 6,
    status: "Initial criticality achieved",
    summary: "A zero-power experiment authorized through NRIC's Nuclear Energy Launch Pad; it is not a power-producing reactor.",
    latest: "DOE reported that Unity achieved initial criticality at about 11:55 p.m. Mountain Time on June 30, fulfilling the three-reactor July 4 target.",
    latestDate: "2026-07",
    next: "Translate the experiment into a licensed power design, customer project, fuel plan, and repeatable commercial delivery process.",
    nextOwner: "Deployable Energy, DOE, and NRC",
    blocker: "Power design, NRC licensing, fuel, customer project, and commercialization",
    confidence: "High",
    verification: "Government-reported",
    source: "https://www.linkedin.com/posts/nuclearenergygov_criticality-number-three-on-june-30-activity-7478100277536043009-NvZD",
    sourceLabel: "DOE Office of Nuclear Energy criticality announcement",
    programs: ["Nuclear Energy Launch Pad"],
    x: 17,
    y: 31,
  },
];

export type Company = {
  slug: string;
  name: string;
  role: string;
  summary: string;
  technology: string;
  projectSlugs: string[];
  source: string;
  sourceLabel: string;
};

export const companies: Company[] = [
  {
    slug: "terrapower",
    name: "TerraPower",
    role: "Reactor developer and project sponsor",
    summary: "Lead developer of the Natrium demonstration project at Kemmerer, Wyoming.",
    technology: "Sodium-cooled fast reactor",
    projectSlugs: ["natrium-kemmerer"],
    source: "https://www.nrc.gov/reactors/new-reactors/advanced/who-were-working-with/past-license-activities/terrapower",
    sourceLabel: "NRC TerraPower record",
  },
  {
    slug: "kairos-power",
    name: "Kairos Power",
    role: "Reactor developer and test-reactor licensee",
    summary: "Developer of the Hermes 2 low-power test reactors in Oak Ridge, Tennessee.",
    technology: "Fluoride salt-cooled high-temperature reactor",
    projectSlugs: ["hermes-2"],
    source: "https://www.nrc.gov/reactors/non-power/new-facility-licensing/hermes2-kairos",
    sourceLabel: "NRC Hermes 2 record",
  },
  {
    slug: "x-energy",
    name: "X-energy",
    role: "Reactor technology provider",
    summary: "Technology developer for the Xe-100 project under review at Dow's Seadrift site in Texas.",
    technology: "High-temperature gas-cooled reactor",
    projectSlugs: ["long-mott-xe-100"],
    source: "https://www.nrc.gov/reactors/new-reactors/advanced/who-were-working-with/applicant-projects/long-mott",
    sourceLabel: "NRC Long Mott dashboard",
  },
  {
    slug: "bwxt",
    name: "BWXT",
    role: "Reactor manufacturer and delivery contractor",
    summary: "Prime industrial partner delivering the Project Pele transportable microreactor for the Department of Defense.",
    technology: "Transportable high-temperature gas reactor",
    projectSlugs: ["project-pele"],
    source: "https://www.energy.gov/ne/articles/department-defense-breaks-ground-project-pele-microreactor",
    sourceLabel: "DOE Project Pele update",
  },
  {
    slug: "radiant-industries",
    name: "Radiant Industries",
    role: "Microreactor developer",
    summary: "Developer of the Kaleidos experiment conditionally selected for testing in the DOME facility.",
    technology: "Gas-cooled microreactor",
    projectSlugs: ["kaleidos-dome", "radiant-kaleidos-ripper-pilot"],
    source: "https://www.energy.gov/ne/demonstration-microreactor-experiments-dome",
    sourceLabel: "DOE DOME program",
  },
  {
    slug: "valar-atomics",
    name: "Valar Atomics",
    role: "Reactor developer",
    summary: "Developer of the Ward 250 zero-power critical experiment in Utah.",
    technology: "Zero-power critical experiment",
    projectSlugs: ["valar-ward-250"],
    source: "https://www.energy.gov/articles/department-energy-celebrates-second-advanced-reactor-achieving-criticality",
    sourceLabel: "DOE criticality announcement",
  },
  {
    slug: "aalo-atomics",
    name: "Aalo Atomics",
    role: "Reactor developer and DOE-authorized operator",
    summary: "Developer of the Aalo Critical Test Reactor and the planned 10 MWe Project Ascension power reactor.",
    technology: "Sodium-cooled modular reactor",
    projectSlugs: ["aalo-x-critical-assembly"],
    source: "https://www.linkedin.com/posts/aalo-atomics_on-july-4-2026-at-1220-am-mt-we-brought-activity-7479885863984713728-HTO7",
    sourceLabel: "Aalo criticality announcement",
  },
  {
    slug: "antares-nuclear",
    name: "Antares Nuclear",
    role: "Microreactor developer",
    summary: "Developer of the Mark-0 zero-power experiment, the first Reactor Pilot Program project to report criticality.",
    technology: "High-temperature heat-pipe microreactor",
    projectSlugs: ["antares-mark-0"],
    source: "https://www.energy.gov/articles/department-energy-celebrates-first-advanced-reactor-criticality",
    sourceLabel: "DOE criticality announcement",
  },
  {
    slug: "atomic-alchemy",
    name: "Atomic Alchemy",
    role: "Reactor and isotope-production developer",
    summary: "Developer of the Groves pilot project in Caldwell County, Texas.",
    technology: "Test and isotope-production reactor",
    projectSlugs: ["atomic-alchemy-groves"],
    source: "https://www.energy.gov/ne/us-department-energy-reactor-pilot-program",
    sourceLabel: "DOE Reactor Pilot Program roster",
  },
  {
    slug: "deep-fission",
    name: "Deep Fission",
    role: "Reactor developer",
    summary: "Developer of a deep-borehole test reactor selected for DOE's pilot pathway.",
    technology: "Deep-borehole reactor",
    projectSlugs: ["deep-fission-dbr"],
    source: "https://www.energy.gov/ne/us-department-energy-reactor-pilot-program",
    sourceLabel: "DOE Reactor Pilot Program roster",
  },
  {
    slug: "last-energy",
    name: "Last Energy",
    role: "Microreactor developer",
    summary: "Developer of the PWR-5 pilot project at Texas A&M's RELLIS campus.",
    technology: "Small pressurized-water reactor",
    projectSlugs: ["last-energy-pwr-5"],
    source: "https://www.energy.gov/ne/us-department-energy-reactor-pilot-program",
    sourceLabel: "DOE Reactor Pilot Program roster",
  },
  {
    slug: "oklo",
    name: "Oklo",
    role: "Fast-reactor and fuel-cycle developer",
    summary: "Developer of the Aurora and Pluto pilot projects selected by DOE.",
    technology: "Fast microreactors",
    projectSlugs: ["oklo-aurora-pilot", "oklo-pluto-pilot"],
    source: "https://www.energy.gov/ne/us-department-energy-reactor-pilot-program",
    sourceLabel: "DOE Reactor Pilot Program roster",
  },
  {
    slug: "natura-resources",
    name: "Natura Resources",
    role: "Molten-salt reactor developer",
    summary: "Developer of the university-based pilot project at Abilene Christian University.",
    technology: "Molten-salt research reactor",
    projectSlugs: ["natura-acu-pilot"],
    source: "https://www.energy.gov/ne/us-department-energy-reactor-pilot-program",
    sourceLabel: "DOE Reactor Pilot Program roster",
  },
  {
    slug: "terrestrial-energy",
    name: "Terrestrial Energy",
    role: "Molten-salt reactor developer",
    summary: "Developer of the TETRA-1 pilot project at Texas A&M's RELLIS campus.",
    technology: "Molten-salt reactor",
    projectSlugs: ["terrestrial-tetra-1"],
    source: "https://www.energy.gov/ne/us-department-energy-reactor-pilot-program",
    sourceLabel: "DOE Reactor Pilot Program roster",
  },
  {
    slug: "deployable-energy",
    name: "Deployable Energy",
    role: "Microreactor developer",
    summary: "Developer of the Unity zero-power experiment authorized through NRIC's Nuclear Energy Launch Pad.",
    technology: "Microreactor experiment",
    projectSlugs: ["deployable-unity"],
    source: "https://www.linkedin.com/posts/nuclearenergygov_criticality-number-three-on-june-30-activity-7478100277536043009-NvZD",
    sourceLabel: "DOE Office of Nuclear Energy announcement",
  },
];

export const federalActions = [
  {
    eo: "EO 14299",
    title: "National security deployment",
    directive: "Operate an Army-regulated reactor at a domestic military installation by September 30, 2028.",
    owner: "Department of Defense / Army",
    status: "In progress",
    next: "Select site and delivery pathway",
    source: "https://www.whitehouse.gov/presidential-actions/2025/05/deploying-advanced-nuclear-reactor-technologies-for-national-security/",
  },
  {
    eo: "EO 14300",
    title: "NRC reform",
    directive: "Revise NRC rules and establish fixed licensing deadlines, including an 18-month ceiling for new-reactor decisions.",
    owner: "Nuclear Regulatory Commission",
    status: "Implementation underway",
    next: "Rules and guidance",
    source: "https://www.whitehouse.gov/presidential-actions/2025/05/ordering-the-reform-of-the-nuclear-regulatory-commission/",
  },
  {
    eo: "EO 14301",
    title: "DOE reactor testing",
    directive: "Create a pilot pathway for reactors outside national laboratories, targeting at least three criticalities by July 4, 2026.",
    owner: "Department of Energy",
    status: "Goal met · DOE reported three; Aalo reported a fourth",
    next: "Operational validation and commercialization",
    source: "https://www.whitehouse.gov/presidential-actions/2025/05/reforming-nuclear-reactor-testing-at-the-department-of-energy/",
  },
  {
    eo: "EO 14302",
    title: "Industrial base",
    directive: "Expand fuel availability, domestic supply chains, workforce, financing, and large-reactor deployment capacity.",
    owner: "DOE and partner agencies",
    status: "In progress",
    next: "Convert conditional support into closed, delivered projects",
    source: "https://www.whitehouse.gov/presidential-actions/2025/05/reinvigorating-the-nuclear-industrial-base/",
  },
];

export const programs = [
  {
    name: "Reactor Pilot Program",
    lead: "DOE Office of Nuclear Energy",
    purpose: "DOE authorization for privately funded test reactors outside national laboratories.",
    measure: "11 initial projects; at least 3 targeted criticalities by July 4, 2026",
    status: "Three pilot criticalities tracked: two DOE-reported and one company-reported",
    source: "https://www.energy.gov/ne/us-department-energy-reactor-pilot-program",
  },
  {
    name: "Advanced Reactor Demonstration Program",
    lead: "DOE Office of Clean Energy Demonstrations",
    purpose: "Cost-shared commercial demonstrations of Natrium and Xe-100 technologies.",
    measure: "$3.2B planned federal investment over seven years, subject to appropriations, with matching industry funds",
    status: "Natrium permitted and under construction; Long Mott license review active",
    source: "https://www.energy.gov/ne/advanced-reactor-demonstration-projects",
  },
  {
    name: "DOME",
    lead: "NRIC / Idaho National Laboratory",
    purpose: "A test bed for fueled microreactor experiments.",
    measure: "Two initial conditional test selections",
    status: "Facility opened in April 2026",
    source: "https://www.energy.gov/ne/demonstration-microreactor-experiments-dome",
  },
  {
    name: "Nuclear Energy Launch Pad",
    lead: "NRIC / Idaho National Laboratory",
    purpose: "DOE-authorized reactor experiments at national-laboratory sites.",
    measure: "First tracked experiment: Deployable Energy Unity",
    status: "Unity achieved DOE-reported initial criticality on June 30, 2026",
    source: "https://www.linkedin.com/posts/nuclearenergygov_criticality-number-three-on-june-30-activity-7478100277536043009-NvZD",
  },
];

export const capital = [
  {
    amount: "$17.5B",
    name: "American Nuclear Supply Chain Loans",
    type: "Conditional federal loan commitment",
    status: "Conditional · not closed",
    date: "2026-06-23",
    purpose: "Long-lead items for five eligible projects tied to ten large reactors",
    source: "https://www.energy.gov/articles/department-energy-announces-american-nuclear-supply-chain-loans",
  },
  {
    amount: "$1.52B",
    name: "Palisades restart loan",
    type: "Closed federal loan",
    status: "Closed · licensing conditions remain",
    date: "2024-09",
    purpose: "Restoration and resumption of service at the 800 MWe Palisades plant",
    source: "https://www.energy.gov/edf/palisades",
  },
  {
    amount: "$3.2B",
    name: "ARDP planned federal cost share",
    type: "Cost-shared demonstration funding",
    status: "Subject to appropriations",
    date: "2020-10",
    purpose: "Natrium and Xe-100 demonstrations, matched by industry partners",
    source: "https://www.energy.gov/ne/articles/us-department-energy-announces-160-million-first-awards-under-advanced-reactor",
  },
];

export const technologies = [
  {
    name: "Sodium fast reactor",
    size: "Hundreds of MWe",
    fuel: "HALEU metal fuel",
    proof: "Licensed construction → operating license → full-power operation",
  },
  {
    name: "High-temperature gas reactor",
    size: "Microreactor to 80 MWe/module",
    fuel: "TRISO particle fuel",
    proof: "Fuel fabrication at scale plus commercial heat-and-power operation",
  },
  {
    name: "Fluoride salt-cooled reactor",
    size: "Test reactor to commercial module",
    fuel: "TRISO pebbles",
    proof: "Hermes test data followed by licensed power-reactor operation",
  },
];

export function stageCounts() {
  return stages.map((stage, index) => ({
    ...stage,
    stage: index + 1,
    count: projects.filter((project) => project.stage === index + 1).length,
    companies: [...new Set(projects
      .filter((project) => project.stage === index + 1)
      .map((project) => project.companySlug))]
      .map((slug) => companies.find((company) => company.slug === slug))
      .filter((company): company is Company => Boolean(company)),
  }));
}
